apiVersion: v1
kind: Service
metadata:
  name: weather-rating-api
  namespace: weather-rating
  labels:
    app: weather-rating-api
    app.kubernetes.io/name: weather-rating
spec:
  type: ClusterIP
  selector:
    app: weather-rating-api
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
